create database sportin5_tpsib17-p4;

create table completesentence(
	completeSentenceID int(9) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	completeSenteceName varchar(255) NOT NULL,
	completeSenteceAnswer varchar(255) NOT NULL,
	completeSentencePath varchar(255) NOT NULL
);

create table guesswho(
	guessWhoID int(9) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	guessWhoName varchar(255) NOT NULL,
	guessWhoAnswer varchar(255) NOT NULL,
	guessWhoPath varchar(255) NOT NULL
);

create table utilizadores(
	id int(9) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome varchar(25) NOT NULL,
	password varchar(50) NOT NULL, 
	email varchar(40) NOT NULL
);



INSERT INTO `guesswho` (`guessWhoID`, `guessWhoName`, `guessWhoAnswer`, `guessWhoPath`) VALUES
(1, 'Andy', 'Andy', '/Projeto/WhoVoice/Episodio1/Andy.mp3'),
(2, 'Andy', 'Andy', '/Projeto/WhoVoice/Episodio1/Andy1.mp3'),
(3, 'Caitlin', 'Caitlin', '/Projeto/WhoVoice/Episodio1/Caitlin.mp3'),
(4, 'Caitlin', 'Caitlin', '/Projeto/WhoVoice/Episodio1/Caitlin1.mp3'),
(5, 'Clarice', 'Clarice', '/Projeto/WhoVoice/Episodio1/Clarice.mp3'),
(6, 'Clarice', 'Clarice', '/Projeto/WhoVoice/Episodio1/Clarice1.mp3'),
(7, 'Jace', 'Jace', '/Projeto/WhoVoice/Episodio1/Jace.mp3'),
(8, 'Jace', 'Jace', '/Projeto/WhoVoice/Episodio1/Jace1.mp3'),
(9, 'John', 'John', '/Projeto/WhoVoice/Episodio1/John.mp3'),
(10, 'John', 'John', '/Projeto/WhoVoice/Episodio1/John1.mp3'),
(11, 'Lauren', 'Lauren', '/Projeto/WhoVoice/Episodio1/Lauren.mp3'),
(12, 'Lauren', 'Lauren', '/Projeto/WhoVoice/Episodio1/Lauren1.mp3'),
(13, 'Lorna', 'Lorna', '/Projeto/WhoVoice/Episodio1/Lorna.mp3'),
(14, 'Lorna', 'Lorna', '/Projeto/WhoVoice/Episodio1/Lorna1.mp3'),
(15, 'Marcos', 'Marcos', '/Projeto/WhoVoice/Episodio1/Marcos.mp3'),
(16, 'Marcos', 'Marcos', '/Projeto/WhoVoice/Episodio1/Marcos1.mp3'),
(17, 'Reed', 'Reed', '/Projeto/WhoVoice/Episodio1/Reed.mp3'),
(18, 'Reed', 'Reed', '/Projeto/WhoVoice/Episodio1/Reed1.mp3'),
(19, 'Sage', 'Sage', '/Projeto/WhoVoice/Episodio1/Sage.mp3'),
(20, 'Sage', 'Sage', '/Projeto/WhoVoice/Episodio1/Sage1.mp3'),
(21, 'Andy', 'Andy', '/Projeto/WhoVoice/Episodio2/Andy.mp3'),
(22, 'Andy', 'Andy', '/Projeto/WhoVoice/Episodio2/Andy1.mp3'),
(23, 'Caitlin', 'Caitlin', '/Projeto/WhoVoice/Episodio2/Caitlin.mp3'),
(24, 'Caitlin', 'Caitlin', '/Projeto/WhoVoice/Episodio2/Caitlin1.mp3'),
(25, 'Jace', 'Jace', '/Projeto/WhoVoice/Episodio2/Jace.mp3'),
(26, 'Jace', 'Jace', '/Projeto/WhoVoice/Episodio2/Jace1.mp3'),
(27, 'John', 'John', '/Projeto/WhoVoice/Episodio2/John.mp3'),
(28, 'Lauren', 'Lauren', '/Projeto/WhoVoice/Episodio2/Lauren.mp3'),
(29, 'Lauren', 'Lauren', '/Projeto/WhoVoice/Episodio2/Lauren1.mp3'),
(30, 'Lorna', 'Lorna', '/Projeto/WhoVoice/Episodio2/Lorna.mp3'),
(31, 'Lorna', 'Lorna', '/Projeto/WhoVoice/Episodio2/Lorna1.mp3'),
(32, 'Marcos', 'Marcos', '/Projeto/WhoVoice/Episodio2/Marcos.mp3'),
(33, 'Marcos', 'Marcos', '/Projeto/WhoVoice/Episodio2/Marcos1.mp3'),
(34, 'Reed', 'Reed', '/Projeto/WhoVoice/Episodio2/Reed.mp3'),
(35, 'Sonya', 'Sonya', '/Projeto/WhoVoice/Episodio2/Sonya.mp3'),
(36, 'Sonya', 'Sonya', '/Projeto/WhoVoice/Episodio2/Sonya1.mp3'),
(37, 'Andy', 'Andy', '/Projeto/WhoVoice/Episodio3/Andy.mp3'),
(38, 'Andy', 'Andy', '/Projeto/WhoVoice/Episodio3/Andy1.mp3'),
(39, 'Caitlin', 'Caitlin', '/Projeto/WhoVoice/Episodio3/Caitlin.mp3'),
(40, 'Caitlin', 'Caitlin', '/Projeto/WhoVoice/Episodio3/Caitlin1.mp3'),
(41, 'Clarice', 'Clarice', '/Projeto/WhoVoice/Episodio3/Clarice.mp3'),
(42, 'Clarice', 'Clarice', '/Projeto/WhoVoice/Episodio3/Clarice1.mp3'),
(43, 'Jace', 'Jace', '/Projeto/WhoVoice/Episodio3/Jace.mp3'),
(44, 'Jace', 'Jace', '/Projeto/WhoVoice/Episodio3/Jace1.mp3'),
(45, 'John', 'John', '/Projeto/WhoVoice/Episodio3/John.mp3'),
(46, 'John', 'John', '/Projeto/WhoVoice/Episodio3/John1.mp3'),
(47, 'Lauren', 'Lauren', '/Projeto/WhoVoice/Episodio3/Lauren.mp3'),
(48, 'Lauren', 'Lauren', '/Projeto/WhoVoice/Episodio3/Lauren1.mp3'),
(49, 'Lorna', 'Lorna', '/Projeto/WhoVoice/Episodio3/Lorna.mp3'),
(50, 'Lorna', 'Lorna', '/Projeto/WhoVoice/Episodio3/Lorna1.mp3'),
(51, 'Marcos', 'Marcos', '/Projeto/WhoVoice/Episodio3/Marcos.mp3'),
(52, 'Marcos', 'Marcos', '/Projeto/WhoVoice/Episodio3/Marcos1.mp3'),
(53, 'Reed', 'Reed', '/Projeto/WhoVoice/Episodio3/Reed.mp3'),
(54, 'Reed', 'Reed', '/Projeto/WhoVoice/Episodio3/Reed1.mp3'),
(55, 'Sonya', 'Sonya', '/Projeto/WhoVoice/Episodio3/Sonya.mp3'),
(56, 'Sonya', 'Sonya', '/Projeto/WhoVoice/Episodio3/Sonya1.mp3'),
(57, 'Uncle Danny', 'Uncle Danny', '/Projeto/WhoVoice/Episodio3/UncleDanny.mp3'),
(58, 'Andy', 'Andy', '/Projeto/WhoVoice/Episodio4/Andy.mp3'),
(59, 'Andy', 'Andy', '/Projeto/WhoVoice/Episodio4/Andy1.mp3'),
(60, 'Caitlin', 'Caitlin', '/Projeto/WhoVoice/Episodio4/Caitlin.mp3'),
(61, 'Caitlin', 'Caitlin', '/Projeto/WhoVoice/Episodio4/Caitlin1.mp3'),
(62, 'Carmen', 'Carmen', '/Projeto/WhoVoice/Episodio4/Carmen.mp3'),
(63, 'Carmen', 'Carmen', '/Projeto/WhoVoice/Episodio4/Carmen1.mp3'),
(64, 'Clarice', 'Clarice', '/Projeto/WhoVoice/Episodio4/Clarice.mp3'),
(65, 'Clarice', 'Clarice', '/Projeto/WhoVoice/Episodio4/Clarice1.mp3'),
(66, 'Jace', 'Jace', '/Projeto/WhoVoice/Episodio4/Jace.mp3'),
(67, 'Jace', 'Jace', '/Projeto/WhoVoice/Episodio4/Jace1.mp3'),
(68, 'John', 'John', '/Projeto/WhoVoice/Episodio4/John.mp3'),
(69, 'John', 'John', '/Projeto/WhoVoice/Episodio4/John1.mp3'),
(70, 'Lauren', 'Lauren', '/Projeto/WhoVoice/Episodio4/Lauren.mp3'),
(71, 'Lauren', 'Lauren', '/Projeto/WhoVoice/Episodio4/Lauren1.mp3'),
(72, 'Lorna', 'Lorna', '/Projeto/WhoVoice/Episodio4/Lorna.mp3'),
(73, 'Lorna', 'Lorna', '/Projeto/WhoVoice/Episodio4/Lorna1.mp3'),
(74, 'Marcos', 'Marcos', '/Projeto/WhoVoice/Episodio4/Marcos.mp3'),
(75, 'Marcos', 'Marcos', '/Projeto/WhoVoice/Episodio4/Marcos1.mp3'),
(76, 'Pulse', 'Pulse', '/Projeto/WhoVoice/Episodio4/Pulse.mp3'),
(77, 'Pulse', 'Pulse', '/Projeto/WhoVoice/Episodio4/Pulse1.mp3'),
(78, 'Reed', 'Reed', '/Projeto/WhoVoice/Episodio4/Reed.mp3'),
(79, 'Reed', 'Reed', '/Projeto/WhoVoice/Episodio4/Reed1.mp3'),
(80, 'Sage', 'Sage', '/Projeto/WhoVoice/Episodio4/Sage.mp3'),
(81, 'Sage', 'Sage', '/Projeto/WhoVoice/Episodio4/Sage1.mp3'),
(82, 'Sonya', 'Sonya', '/Projeto/WhoVoice/Episodio4/Sonya.mp3'),
(83, 'Sonya', 'Sonya', '/Projeto/WhoVoice/Episodio4/Sonya1.mp3'),
(84, 'Andy', 'Andy', '/Projeto/WhoVoice/Episodio5/Andy.mp3'),
(85, 'Clarice', 'Clarice', '/Projeto/WhoVoice/Episodio5/Clarice.mp3'),
(86, 'Fade', 'Fade', '/Projeto/WhoVoice/Episodio5/Fade.mp3'),
(87, 'Jace', 'Jace', '/Projeto/WhoVoice/Episodio5/Jace.mp3'),
(88, 'John', 'John', '/Projeto/WhoVoice/Episodio5/John.mp3'),
(89, 'Caitlin', 'Caitlin', '/Projeto/WhoVoice/Episodio5/Caitlin.mp3'),
(90, 'Lauren', 'Lauren', '/Projeto/WhoVoice/Episodio5/Lauren.mp3'),
(91, 'Lorna', 'Lorna', '/Projeto/WhoVoice/Episodio5/Lorna.mp3'),
(92, 'Marcos', 'Marcos', '/Projeto/WhoVoice/Episodio5/Marcos.mp3'),
(93, 'Paula', 'Paula', '/Projeto/WhoVoice/Episodio5/Paula.mp3'),
(94, 'Reed', 'Reed', '/Projeto/WhoVoice/Episodio5/Reed.mp3'),
(95, 'Sage', 'Sage', '/Projeto/WhoVoice/Episodio5/Sage.mp3'),
(96, 'Shatter', 'Shatter', '/Projeto/WhoVoice/Episodio5/Shatter.mp3'),
(97, 'Sonya', 'Sonya', '/Projeto/WhoVoice/Episodio5/Sonya.mp3'),
(98, 'Andy', 'Andy', '/Projeto/WhoVoice/Episodio6/Andy.mp3'),
(99, 'Caitlin', 'Caitlin', '/Projeto/WhoVoice/Episodio6/Caitlin.mp3'),
(100, 'Clarice', 'Clarice', '/Projeto/WhoVoice/Episodio6/Clarice.mp3'),
(101, 'Jace', 'Jace', '/Projeto/WhoVoice/Episodio6/Jace.mp3'),
(102, 'John', 'John', '/Projeto/WhoVoice/Episodio6/John.mp3'),
(103, 'Lauren', 'Lauren', '/Projeto/WhoVoice/Episodio6/Lauren.mp3'),
(104, 'Lorna', 'Lorna', '/Projeto/WhoVoice/Episodio6/Lorna.mp3'),
(105, 'Marcos', 'Marcos', '/Projeto/WhoVoice/Episodio6/Marcos.mp3'),
(106, 'Reed', 'Reed', '/Projeto/WhoVoice/Episodio6/Reed.mp3'),
(107, 'Wes', 'Wes', '/Projeto/WhoVoice/Episodio6/Wes.mp3'),
(108, 'Andy', 'Andy', '/Projeto/WhoVoice/Episodio7/Andy.mp3'),
(109, 'Caitlin', 'Caitlin', '/Projeto/WhoVoice/Episodio7/Caitlin.mp3'),
(110, 'DrCampbell', 'Dr Campbell', '/Projeto/WhoVoice/Episodio7/DrCampbell.mp3'),
(111, 'Jace', 'Jace', '/Projeto/WhoVoice/Episodio7/Jace.mp3'),
(112, 'John', 'John', '/Projeto/WhoVoice/Episodio7/John.mp3'),
(113, 'Lauren', 'Lauren', '/Projeto/WhoVoice/Episodio7/Lauren.mp3'),
(114, 'Lorna', 'Lorna', '/Projeto/WhoVoice/Episodio7/Lorna.mp3'),
(115, 'Marcos', 'Marcos', '/Projeto/WhoVoice/Episodio7/Marcos.mp3'),
(116, 'Reed', 'Reed', '/Projeto/WhoVoice/Episodio7/Reed.mp3'),
(117, 'Wes', 'Wes', '/Projeto/WhoVoice/Episodio7/Wes.mp3'),
(118, 'Andy', 'Andy', '/Projeto/WhoVoice/Episodio8/Andy.mp3'),
(119, 'Caitlin', 'Caitlin', '/Projeto/WhoVoice/Episodio8/Caitlin.mp3'),
(120, 'Clarice', 'Clarice', '/Projeto/WhoVoice/Episodio8/Clarice.mp3'),
(121, 'Esme', 'Esme', '/Projeto/WhoVoice/Episodio8/Esme.mp3'),
(122, 'Lauren', 'Lauren', '/Projeto/WhoVoice/Episodio8/Lauren.mp3'),
(123, 'Lorna', 'Lorna', '/Projeto/WhoVoice/Episodio8/Lorna.mp3'),
(124, 'Marcos', 'Marcos', '/Projeto/WhoVoice/Episodio8/Marcos.mp3'),
(125, 'Otto', 'Otto', '/Projeto/WhoVoice/Episodio8/Otto.mp3'),
(126, 'Reed', 'Reed', '/Projeto/WhoVoice/Episodio8/Reed.mp3'),
(127, 'Sonya', 'Sonya', '/Projeto/WhoVoice/Episodio8/Sonya.mp3');

